name: test env
description: testing is composite action can receive env var

inputs:
  my_name:
    description: name
    required: true
  my_age:
    description: age
    required: true

runs:
  using: composite
  steps:
    - name: check inputs
      shell: bash
      run: |
        echo ${{ inputs.my_name }} is not ${{ inputs.my_age }}
        echo my_name: $my_name , my_age: $my_age first_name: $first_name , last_name: $last_name