name: share between jobs/runner using artifact
on: workflow_dispatch

jobs:
  upload-to-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: generate file
        id: if-test
        run: ls -lah >> ./abcd.txt
      
      - name: if not
        if: steps.if-test.output.abc == null
        run: echo 'NOT FOUND'

        
      - name: checkout
        uses: actions/checkout@v3

      - name: generate file
        run: ls -lah >> ./abcd.txt

      - name: check the file
        run: cat ./abcd.txt

      - name: upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./abcd.txt


  get-artifact:
    runs-on: ubuntu-latest
    needs: [upload-to-artifact]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          # path: .


      - name: output content 
        run: cat ./abcd.txt
          
   