name: artifact-upload-docker-image
on:
  workflow_dispatch:
    
jobs:
  build-upload-image:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v3

     - name: login to github container registry
       uses: docker/login-action@v2
       with: 
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: build image
       run: docker build -t ghcr.io/${{ github.repository }} .
     
     - name: push image
       run: docker push ghcr.io/${{ github.repository }}

     - name: check image
       run: docker images
  
  pull-image:
    runs-on: ubuntu-latest
    needs: [build-upload-image]
    steps:
      - name: login to github container registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: check image before pull
        run: docker images

      - name: pull image
        run: docker pull ghcr.io/${{ github.repository }}

      - name: check image after pull
        run: docker images
        
