name: branch_name_var
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
    
jobs:
  action-in-out-put:
   uses: bruce1237/github-workflow-center/.github/workflows/branch_name.yml@myTest
   with:
    input_var: ${{ github.ref_name }}
    branch_name: ${{ inputs.tags }}