name: run clair-scan
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
    
  workflow_dispatch:
   
jobs:
  clair-scan:
    uses: bruce1237/github-workflow-center/.github/workflows/clair-scan.yml@main
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ github.ref_name }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
