name: run clair-scan
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
    
  workflow_dispatch:
   
jobs:
  clair-scan:
   runs-on: ubuntu-latest
   steps:
      - name: docker login
        uses: bruce1237/github-workflow-center/.github/actions/docker-login@main
        with:
          github_token: ${{ github.TOKEN }}

      - name: try-1
        run: |
          echo $'
              FROM amazonlinux:2
              RUN curl -L \
                  https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 \
                  -o clair-scanner && \
                  chmod +x ./clair-scanner
            ' | docker build -t clair-scanner -
      
      - name: pull the image
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: checkout clair
        uses: actions/checkout@v3
        with:
          repository: arminc/clair-scanner
      
      - name: copy file
        run: |
          cp ./example-run.sh clair-scanner
          chmod +x clair-scanner
      
      - name: check files
        run: |
          ls -lah
          ls -lah /

      - name: check images
        run: |
          docker images


      - name: run scan
        run: |
          touch clair-whitelist.yml
          # ./clair-scanner -r report.json -l result.log -w clair-whitelist.yml ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ./clair-scanner ghcr.io/${{ github.repository }}:${{ github.ref_name }} >> report.json

      - name: check log file
        run: cat result.log
