name: remove package
on:
  push:
    branches:
      - "myt1"
  workflow_dispatch:
    
jobs:
  remove-image:
    runs-on: ubuntu-latest
    steps:
      - name: login to github container registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: remove package
        uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.actor }}
          package-name: ${{ github.repository}}:${{ github.ref_name }}
          package-type: 'container'
          

