name: remove package
on:
  push:
    branches:
      - "myt1"
  workflow_dispatch:
    
jobs:
   remove-image:
     runs-on: ubuntu-latest
     needs: [build-upload-image,pull-image]
     steps:
      - name: remove package
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.repository }}
          package-type: 'container'


