name: remove package
on:
  push:
    branches:
      - "myt1"
  workflow_dispatch:
    
jobs:
  remove-image:
    runs-on: ubuntu-latest
    steps:
      - name: remove package
        uses: actions/delete-package-versions@v4
        with:
          owner: 'github'
          package-name: github-action-workflow-hero #${{ github.repository }}
          package-type: 'container'


