name: share-image
on:
  workflow_dispatch:
    
jobs:
  create-image:
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker_build_files/Dockerfile
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
      
      - name: check image
        run: docker image ls -a

  get-image:
    runs-on: ubuntu-latest
    needs: create-image
    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      
      - name: load image
        run: docker load --input /tmp/myimage.tar
      
      - name: check image
        run: docker image ls -a
        

    