name: testing-actions
on:
  workflow_dispatch:
    
jobs:
  call-dash-name:
   runs-on: ubuntu-latest
   steps:
     - name: call dash-name
       uses: bruce1237/github-workflow-center/.github/actions/dash-branch-name@main