name: test_env_var
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  first_name: bo
  last_name: sun

jobs:
  onlyTestEnv:
    runs-on: ubuntu-latest
    steps:
      - name: using env var
        run: echo ${{ env.first_name }}_${{ env.last_name }} is my name

      - name: check composite action
        uses: bruce1237/github-action-workflow-hero/.github/actions/env_test@main
        with:
          my_name: ${{ env.first_name }}
          my_age: ${{ env.last_name }}

  testJobEnv:
    runs-on: ubuntu-latest
    outputs:
      my_phone: ${{ steps.setSec.outputs.my_phone }}
    steps:
      - name: using step env
        env:
          my_name: bo_sun
          my_age: 40
        run: |
          echo $my_name is $my_age $MY_WC
      
      - name: set secret to outputs
        id: setSec
        run:
          echo "my_phone=${{ secrets.MY_SE }}" >> $GITHUB_OUTPUT

      - name: check composite action
        uses: bruce1237/github-action-workflow-hero/.github/actions/env_test@main
        env:
          my_name: ${{ secrets.MY_SE }}
          my_age: ${{ env.last_name }}
  
  compositeEnvTest:
    needs: testJobEnv
    uses: bruce1237/github-workflow-center/.github/workflows/env_test.yml@main
    with:
      my_name: ${{ needs.testJobEnv.outputs.my_phone }}
      my_age: abc
   