name: using composite action
on: workflow_dispatch

jobs:
  getRepo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       
     - name: check before
       run: echo ${{ env.branch_name }}

     - name: set env-ref-name
       run: echo "ref_name='b/1/a" >> $GITHUB_ENV
       
     - name: run the composite action
       uses: ./.github/actions/uppercase-repo-name

     - name: check env-branch-name value
       run: echo ${{ env.branch_name }}

     - name: get repo name
       run: echo ${{ env.repo }}
    