name: using composite action
on: workflow_dispatch

jobs:
  getRepo:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       
     - name: run the composite action
       uses: ./.github/actions/uppercase-repo-name

     - name: check env-branch-name value
       uses: echo ${{ env.branch_name }}

     - name: get repo name
       run: echo ${{ env.repo }}
    